# API specification
api:
  name: "${project.artifactId}"
  version: "${project.version}"
  # Replace with respective autodiscovery id
  autodiscoveryID: ""

# Listener configuration
https:
  port: "8082"
  private:
    port: "8092"
  host: "0.0.0.0"
  readTimeOut: "30000"
  certificate:
    path: "certificate/mule-server-keystore.jks"
http:
  host: "0.0.0.0"
  private:
    port: "8091"
  port: "8081"
  readTimeOut: "30000"

# API Configurations
sample-prc-api:
  http-listener:
    path: "/api/*"
  http-client:
    client-id:  "Client Id overridden at deploy time"  
    client-secret: "Client secret overridden at deploy time"

### JSON Logger configuration ###
# Indicate which fields should not be logged
json:
  logger:
    disabled:
      fields: "content"

# Retry
retry:
  http: 
    delayMillisecs: "3000"
    numRetries: "3"
  amq:
    delayMillisecs: "3000"
    numRetries: "3"
    
# Reconnection
amq:
  exchange:
    url: "https://mq-us-east-1.anypoint.mulesoft.com/api/v1"
    name: "ex-trade-account-registration"
  connection:
    timeout: "30000"
  reconnection:
    frequency: "2000"
    attempts: "2"
  delivery:
    delayMillisecs: "0"