resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource
      tag: v0.23.0

resources:
  - name: source-code-resource
    type: git
    icon: github
    check_every: 24h
    webhook_token: ((github_webhook_token))
    source:
      access_token: ((github_access_token))
      uri: git@github.hy-vee.cloud:((organization))/((repository)).git
      branch: {{branch}}
      v3_endpoint: https://github.hy-vee.cloud/api/v3/
      v4_endpoint: https://github.hy-vee.cloud/api/graphql
  - name: pipeline-resource
    type: git
    icon: github
    check_every: 24h
    webhook_token: ((github_webhook_token))
    source:
      access_token: ((github_access_token))
      uri: git@github.hy-vee.cloud:((organization))/((pipeline-repository)).git
      branch: {{pipeline-branch}}
      v3_endpoint: https://github.hy-vee.cloud/api/v3/
      v4_endpoint: https://github.hy-vee.cloud/api/graphql
  - name: version-resource
    type: semver
    icon: github
    check_every: 24h
    webhook_token: ((github_webhook_token))
    source:
      driver: git
      initial_version: 0.0.1
      access_token: ((github_access_token))
      uri: git@github.hy-vee.cloud:((organization))/((repository)).git
      branch: {{branch}}
      v3_endpoint: https://github.hy-vee.cloud/api/v3/
      v4_endpoint: https://github.hy-vee.cloud/api/graphql
      file: src/main/resources/version

jobs:
- name: job-publish-and-deploy-asset
  serial: true
  plan:
  - get: source-code-resource
    trigger: true
  - get: pipeline-resource
  - get: version-resource
    params: { pre: rc }
  - task: build-and-verify-asset
    file: pipeline-resource/tasks/maven-verify.yml
    input_mapping: {source-code: source-code-resource, pipeline: pipeline-resource, version: version-resource}
    params:
      BRANCH: {{source-code-resource-branch}}
      M2_SETTINGS_MULE_EE_REPO_USERNAME: {{m2-settings-mule_ee_repo-username}}
      M2_SETTINGS_MULE_EE_REPO_PASSWORD: {{m2-settings-mule_ee_repo-password}}
      M2_SETTINGS_EXCHANGE_REPO_ORG_ID: {{m2-settings-exchange_repo-org-id}}
      M2_SETTINGS_EXCHANGE_REPO_USERNAME: {{m2-settings-exchange_repo-username}}
      M2_SETTINGS_EXCHANGE_REPO_PASSWORD: {{m2-settings-exchange_repo-password}}
  - task: deploy-asset
    file: pipeline-resource/tasks/maven-deploy.yml
    input_mapping: {source-code: source-code-resource, pipeline: pipeline-resource, version: version-resource}
    params:
      BRANCH: {{source-code-resource-branch}}
      M2_SETTINGS_MULE_EE_REPO_USERNAME: {{m2-settings-mule_ee_repo-username}}
      M2_SETTINGS_MULE_EE_REPO_PASSWORD: {{m2-settings-mule_ee_repo-password}}
      M2_SETTINGS_EXCHANGE_REPO_ORG_ID: {{m2-settings-exchange_repo-org-id}}
      M2_SETTINGS_EXCHANGE_REPO_USERNAME: {{m2-settings-exchange_repo-username}}
      M2_SETTINGS_EXCHANGE_REPO_PASSWORD: {{m2-settings-exchange_repo-password}}
      MULE_ENV_NAME: {{mule-env-name}}
      ANYPOINT_PLATFORM_URL: {{anypoint-platform-url}}
      CONNECTED_APP_CLIENT_ID: {{connected-app-client-id}}
      CONNECTED_APP_CLIENT_SECRET: {{connected-app-client-secret}}
      CONNECTED_APP_GRANT_TYPE: {{connected-app-grant-type}}
      APPLICATION_NAME: {{application-name}}
      ENVIRONMENT_NAME: {{environment-name}}
      DEPLOYMENT_WORKERS: {{deployment-workers}}
      DEPLOYMENT_REGION: {{deployment-region}}
      DEPLOYMENT_WORKER_TYPE: {{deployment-worker-type}}
      DEPLOYMENT_MULE_RUNTIME: {{deployment-mule-runtime}}

- name: increase-major-version
  serial: true
  plan:
  - put: version-resource
    params: { bump: major }

- name: increase-minor-version
  serial: true
  plan:
  - put: version-resource
    params: { bump: minor }

- name: increase-patch-version
  serial: true
  plan:
  - put: version-resource
    params: { bump: patch }

groups:
- name: publish-and-deploy
  jobs:
  - job-publish-and-deploy-asset
- name: version-management
  jobs:
  - increase-major-version
  - increase-minor-version
  - increase-patch-version
