
#Common properties
common:
  errors:
    error-code-400: "BAD_REQUEST"
    error-code-404: "NOT_FOUND"
    error-code-405: "METHOD_NOT_ALLOWED"
    error-code-406: "NOT_ACCEPTABLE"
    error-code-415: "UNSUPPORTED_MEDIA_TYPE"
    error-code-500: "INTERNAL_SERVER_ERROR"
    error-code-501: "NOT_IMPLEMENTED"
  #notification process api configuration
  notifications-prc-api:
    #Replace with appropriate application host.
    host: "accel-notifications-prc-api-v1-dev.ca-c1.cloudhub.io"
    port: "80"
    root: "/api"
   #notification.send valid values, email,sms , all and None, if value is set as None  - no notification is sent
  notifications:
    send: "none"
    email:
      # Replace with appropriate email address
      from-address: "noreply@invalid.com"
      #Replace with appropriate email address
      to-address: "nodest@invalid.com"
    sms:
      #Replace with appropriate number
      from-number: "18005551234"
      #Replace with appropriate number
      to-number: "18005551234"

notification-prc-api:
  #Replace with respective client application
  client-id: ""
  client-secret: ""
  
keystore:
  alias:    "solutionsteam"   
  key-pass: "mulesoft"
  password: "mulesoft"
  path: "keystore/accelerator-keystore.jks"