# use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.

#salesforce:
#  consumerKey: "![]"
#  principal: "![]"
#  storePassword: "![]"
#  tokenEndPoint: "https://test.salesforce.com/services/oauth2/token"
#  audienceUrl: "https://test.salesforce.com"
#  keyStore: ""